# Generated by Django 6.1 on 2026-10-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Référence médicament'),
        ),
    ]
