from .consultation import *
from .hospitalisation import *
from .rendez_vous import *
from .diagnostic import *
from .signe_vital import *
from .acte_medical import *
from .arret_travail import *
from .certificat_medical import *
from .orientation import *
from .referement import *
from .historique_consultation import *
