from .general import *
from .actes import *
from .consultations import *
from .examens import *
from .hospitalisation import *
from .personnel import *
from .cliniques import *
from .conventions import *
from .pharmacies import *
from .pharmacies_internes import *
from .pharmacie_partenaire import *
from .catalogue_pharmacies_partenaires import *
from .tarifs_pharmacies_partenaires import *