# Generated by Django 6.1 on 2026-09-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0003_departement_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationetablissement',
            name='module_conventions_actif',
            field=models.BooleanField(default=False, help_text="Active la gestion des entreprises tierces affiliées : cet établissement reçoit des patients qu'elles réfèrent pour certaines pathologies conventionnées", verbose_name='Module conventions entreprises'),
        ),
    ]
