# Generated by Django 6.1 on 2026-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0004_configurationetablissement_module_conventions_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la spécialité')),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, help_text='Classe icône Remix Icon (ex : ri-tooth-line, ri-eye-line)', max_length=50, null=True, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'db_table': 'specialites',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='specialites',
            field=models.ManyToManyField(blank=True, help_text="Spécialités médicales pratiquées, détermine les modules visibles dans l'application", related_name='etablissements', to='parametrage_general.specialite', verbose_name='Spécialités'),
        ),
    ]
