# Generated by Django 6.1 on 2026-09-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0005_specialite_configurationetablissement_specialites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurationetablissement',
            options={'ordering': ['nom_etablissement'], 'verbose_name': 'Configuration établissement', 'verbose_name_plural': 'Configurations établissements'},
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='boite_postale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Boîte postale'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='devise',
            field=models.CharField(default='GNF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='fuseau_horaire',
            field=models.CharField(default='Africa/Conakry', max_length=50, verbose_name='Fuseau horaire'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='identifiant_administratif',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifiant administratif'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='numero_agrement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'agrément"),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='numero_autorisation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'autorisation"),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='numero_fiscal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro fiscal'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='pays',
            field=models.CharField(default='Guinée', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='registre_commerce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registre de commerce'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='telephone_secondaire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone secondaire'),
        ),
        migrations.AddField(
            model_name='configurationetablissement',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements', to='parametrage_general.ville', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='module_conventions_actif',
            field=models.BooleanField(default=False, help_text='Active la gestion des entreprises tierces affiliées', verbose_name='Module conventions entreprises'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='specialites',
            field=models.ManyToManyField(blank=True, help_text="Spécialités médicales pratiquées dans l'établissement", related_name='etablissements', to='parametrage_general.specialite', verbose_name='Spécialités'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('clinique', 'Clinique privée'), ('hopital_public', 'Hôpital public'), ('hopital_prive', 'Hôpital privé'), ('centre_entreprise', "Centre médical d'entreprise / Prise en charge"), ('cabinet', 'Cabinet médical'), ('centre_sante', 'Centre de santé'), ('cabinet_dentaire', 'Cabinet dentaire'), ('cabinet_ophtalmologique', 'Cabinet ophtalmologique'), ('polyclinique', 'Polyclinique'), ('centre_imagerie', "Centre d'imagerie"), ('laboratoire', 'Laboratoire'), ('autre', 'Autre établissement de santé')], default='clinique', max_length=30, verbose_name="Type d'établissement"),
        ),
    ]
