# Generated by Django 6.1 on 2026-09-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0006_alter_configurationetablissement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationetablissement',
            name='module_conventions_actif',
            field=models.BooleanField(default=False, help_text='Active la gestion des conventions et entreprises partenaires', verbose_name='Module conventions entreprises'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='module_prise_en_charge_actif',
            field=models.BooleanField(default=False, help_text='Active les modules liés à la prise en charge entreprise', verbose_name='Module prise en charge actif'),
        ),
        migrations.AlterField(
            model_name='configurationetablissement',
            name='type_etablissement',
            field=models.CharField(choices=[('clinique', 'Clinique privée'), ('hopital_public', 'Hôpital public'), ('hopital_prive', 'Hôpital privé'), ('cabinet', 'Cabinet médical'), ('centre_sante', 'Centre de santé'), ('cabinet_dentaire', 'Cabinet dentaire'), ('cabinet_ophtalmologique', 'Cabinet ophtalmologique'), ('polyclinique', 'Polyclinique'), ('centre_imagerie', "Centre d'imagerie"), ('laboratoire', 'Laboratoire'), ('autre', 'Autre établissement de santé')], default='clinique', max_length=30, verbose_name="Type d'établissement"),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='icone',
            field=models.CharField(blank=True, help_text='Classe icône Remix Icon', max_length=50, null=True, verbose_name='Icône'),
        ),
        migrations.CreateModel(
            name='UniteMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=150, verbose_name="Nom de l'unité")),
                ('type_unite', models.CharField(choices=[('infirmerie', 'Infirmerie'), ('laboratoire', 'Laboratoire'), ('pharmacie', 'Pharmacie'), ('imagerie', 'Imagerie médicale'), ('consultation', 'Consultation'), ('urgences', 'Urgences'), ('hospitalisation', 'Hospitalisation'), ('autre', 'Autre unité médicale')], max_length=30, verbose_name="Type d'unité")),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_medicales', to='parametrage_general.site', verbose_name='Site')),
                ('specialites', models.ManyToManyField(blank=True, related_name='unites_medicales', to='parametrage_general.specialite', verbose_name='Spécialités')),
            ],
            options={
                'verbose_name': 'Unité médicale',
                'verbose_name_plural': 'Unités médicales',
                'db_table': 'unites_medicales',
                'ordering': ['nom'],
            },
        ),
    ]
