# Generated by Django 6.1 on 2026-09-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0007_alter_configurationetablissement_module_conventions_actif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie d’acte',
                'verbose_name_plural': 'Catégories d’actes',
                'db_table': 'parametrage_categories_actes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('necessite_medicament', models.BooleanField(default=False, verbose_name='Nécessite un médicament')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actes', to='parametrage_general.categorieacte', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Acte médical',
                'verbose_name_plural': 'Actes médicaux',
                'db_table': 'parametrage_actes_medicaux',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TarifActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='parametrage_general.actemedical', verbose_name='Acte médical')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_actes', to='parametrage_general.configurationetablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Tarif d’acte',
                'verbose_name_plural': 'Tarifs des actes',
                'db_table': 'parametrage_tarifs_actes',
                'ordering': ['-date_debut'],
            },
        ),
    ]
