# Generated by Django 6.1 on 2026-09-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0008_categorieacte_actemedical_tarifacte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de consultation',
                'verbose_name_plural': 'Types de consultation',
                'db_table': 'parametrage_types_consultations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TarifConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_consultations', to='parametrage_general.configurationetablissement', verbose_name='Établissement')),
                ('type_consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='parametrage_general.typeconsultation', verbose_name='Type de consultation')),
            ],
            options={
                'verbose_name': 'Tarif de consultation',
                'verbose_name_plural': 'Tarifs des consultations',
                'db_table': 'parametrage_tarifs_consultations',
                'ordering': ['-date_debut'],
            },
        ),
    ]
