# Generated by Django 6.1 on 2026-09-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0009_typeconsultation_tarifconsultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeconsultation',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Type de consultation', 'verbose_name_plural': 'Types de consultation'},
        ),
        migrations.AddField(
            model_name='typeconsultation',
            name='categorie',
            field=models.CharField(choices=[('generale', 'Consultation générale'), ('specialisee', 'Consultation spécialisée'), ('urgence', 'Urgence'), ('suivi', 'Suivi et contrôle'), ('preventive', 'Prévention'), ('travail', 'Médecine du travail'), ('teleconsultation', 'Téléconsultation'), ('autre', 'Autre consultation')], default='generale', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='typeconsultation',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='tarifconsultation',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='typeconsultation',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='typeconsultation',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typeconsultation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='typeconsultation',
            name='nom',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom'),
        ),
    ]
