# Generated by Django 6.1 on 2026-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0010_alter_typeconsultation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=191, verbose_name='Motif')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motif de consultation',
                'verbose_name_plural': 'Motifs de consultation',
                'db_table': 'parametrage_motifs_consultation',
                'ordering': ['motif'],
            },
        ),
        migrations.CreateModel(
            name='Posologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=191, verbose_name='Posologie')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posologie',
                'verbose_name_plural': 'Posologies',
                'db_table': 'parametrage_posologies',
                'ordering': ['libelle'],
            },
        ),
    ]
