# Generated by Django 6.1 on 2026-09-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0011_motifconsultation_posologie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=191, unique=True, verbose_name='Dosage')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dosage',
                'verbose_name_plural': 'Dosages',
                'db_table': 'parametrage_dosages',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Forme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forme pharmaceutique',
                'verbose_name_plural': 'Formes pharmaceutiques',
                'db_table': 'parametrage_formes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='VoieAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Voie d'administration",
                'verbose_name_plural': "Voies d'administration",
                'db_table': 'parametrage_voies_administration',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
