# Generated by Django 6.1 on 2026-09-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0012_dosage_forme_voieadministration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Catégorie d'examen",
                'verbose_name_plural': "Catégories d'examens",
                'db_table': 'parametrage_categories_examens',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unite', models.CharField(blank=True, max_length=100, verbose_name='Unité')),
                ('valeur_reference', models.TextField(blank=True, verbose_name='Valeur de référence')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'db_table': 'parametrage_examens',
                'ordering': ['type_examen__categorie__ordre', 'type_examen__ordre', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='TarifExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_examens', to='parametrage_general.configurationetablissement', verbose_name='Établissement')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='parametrage_general.examen', verbose_name='Examen')),
            ],
            options={
                'verbose_name': "Tarif d'examen",
                'verbose_name_plural': 'Tarifs des examens',
                'db_table': 'parametrage_tarifs_examens',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types_examens', to='parametrage_general.categorieexamen', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': "Type d'examen",
                'verbose_name_plural': "Types d'examens",
                'db_table': 'parametrage_types_examens',
                'ordering': ['categorie__ordre', 'ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='type_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='parametrage_general.typeexamen', verbose_name="Type d'examen"),
        ),
        migrations.AddConstraint(
            model_name='typeexamen',
            constraint=models.UniqueConstraint(fields=('categorie', 'nom'), name='unique_type_examen_categorie_nom'),
        ),
    ]
