# Generated by Django 6.1 on 2026-09-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0013_categorieexamen_examen_tarifexamen_typeexamen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=191, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Motif d'hospitalisation",
                'verbose_name_plural': "Motifs d'hospitalisation",
                'db_table': 'parametrage_motifs_hospitalisation',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RegimeAlimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Régime alimentaire',
                'verbose_name_plural': 'Régimes alimentaires',
                'db_table': 'parametrage_regimes_alimentaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacite', models.PositiveIntegerField(default=1, verbose_name='Capacité')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambre',
                'db_table': 'parametrage_types_chambres',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de séjour',
                'verbose_name_plural': 'Types de séjour',
                'db_table': 'parametrage_types_sejours',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeSoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('categorie', models.CharField(blank=True, max_length=150, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de soin',
                'verbose_name_plural': 'Types de soins',
                'db_table': 'parametrage_types_soins',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de sortie',
                'verbose_name_plural': 'Types de sortie',
                'db_table': 'parametrage_types_sortie',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TarifSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('unite_facturation', models.CharField(default='jour', max_length=50, verbose_name='Unité de facturation')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_sejours', to='parametrage_general.configurationetablissement', verbose_name='Établissement')),
                ('type_chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_sejours', to='parametrage_general.typechambre', verbose_name='Type de chambre')),
                ('type_sejour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='parametrage_general.typesejour', verbose_name='Type de séjour')),
            ],
            options={
                'verbose_name': 'Tarif de séjour',
                'verbose_name_plural': 'Tarifs des séjours',
                'db_table': 'parametrage_tarifs_sejours',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='UniteHospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacite', models.PositiveIntegerField(default=0, verbose_name='Capacité')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites_hospitalisation', to='parametrage_general.configurationetablissement', verbose_name='Établissement')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unites_hospitalisation', to='parametrage_general.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': "Unité d'hospitalisation",
                'verbose_name_plural': "Unités d'hospitalisation",
                'db_table': 'parametrage_unites_hospitalisation',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('etage', models.CharField(blank=True, max_length=100, verbose_name='Étage')),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('capacite', models.PositiveIntegerField(default=1, verbose_name='Capacité')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='parametrage_general.configurationetablissement', verbose_name='Établissement')),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='parametrage_general.typechambre', verbose_name='Type de chambre')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='parametrage_general.unitehospitalisation', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'db_table': 'parametrage_chambres',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupé'), ('reserve', 'Réservé'), ('maintenance', 'Maintenance'), ('inactif', 'Inactif')], default='disponible', max_length=20, verbose_name='Statut')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lits', to='parametrage_general.chambre', verbose_name='Chambre')),
            ],
            options={
                'verbose_name': 'Lit',
                'verbose_name_plural': 'Lits',
                'db_table': 'parametrage_lits',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('chambre', 'code'), name='unique_lit_chambre_code')],
            },
        ),
        migrations.AddConstraint(
            model_name='unitehospitalisation',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='unique_unite_hospitalisation_etablissement_code'),
        ),
        migrations.AddConstraint(
            model_name='chambre',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='unique_chambre_etablissement_code'),
        ),
    ]
