# Generated by Django 6.1 on 2026-09-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0014_motifhospitalisation_regimealimentaire_typechambre_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unitehospitalisation',
            name='unique_unite_hospitalisation_etablissement_code',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chambres', to='parametrage_general.unitemedicale', verbose_name='Unité médicale'),
        ),
        migrations.DeleteModel(
            name='UniteHospitalisation',
        ),
    ]
