# Generated by Django 6.1 on 2026-09-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0015_remove_unitehospitalisation_unique_unite_hospitalisation_etablissement_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtablissementPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'établissement")),
                ('code', models.CharField(help_text="Identifiant unique de l'établissement partenaire.", max_length=50, unique=True, verbose_name='Code partenaire')),
                ('type_partenaire', models.CharField(choices=[('clinique', 'Clinique privée'), ('hopital_public', 'Hôpital public'), ('hopital_prive', 'Hôpital privé'), ('polyclinique', 'Polyclinique'), ('centre_medical', 'Centre médical'), ('cabinet_medical', 'Cabinet médical'), ('cabinet_dentaire', 'Cabinet dentaire'), ('cabinet_ophtalmologique', 'Cabinet ophtalmologique'), ('laboratoire', 'Laboratoire'), ('centre_imagerie', "Centre d'imagerie"), ('centre_specialise', 'Centre spécialisé'), ('autre', 'Autre structure de santé')], default='clinique', max_length=40, verbose_name='Type de structure')),
                ('pays', models.CharField(default='Guinée', max_length=100, verbose_name='Pays')),
                ('quartier', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quartier')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('nom_contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du contact')),
                ('fonction_contact', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction du contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du contact')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail du contact')),
                ('numero_agrement', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'agrément")),
                ('numero_autorisation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'autorisation")),
                ('numero_fiscal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro fiscal')),
                ('registre_commerce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registre de commerce')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('accepte_orientation', models.BooleanField(default=True, help_text="Indique si l'établissement accepte les patients orientés par SANITA.", verbose_name='Accepte les orientations')),
                ('statut_partenaire', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='actif', max_length=20, verbose_name='Statut du partenariat')),
                ('date_debut_partenariat', models.DateField(blank=True, null=True, verbose_name='Date de début du partenariat')),
                ('date_fin_partenariat', models.DateField(blank=True, null=True, verbose_name='Date de fin du partenariat')),
                ('specialites', models.ManyToManyField(blank=True, related_name='etablissements_partenaires', to='parametrage_general.specialite', verbose_name='Spécialités')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements_partenaires', to='parametrage_general.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Établissement partenaire',
                'verbose_name_plural': 'Établissements partenaires',
                'db_table': 'etablissements_partenaires',
                'ordering': ['nom'],
            },
        ),
    ]
