# Generated by Django 6.1 on 2026-09-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0016_etablissementpartenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la pharmacie')),
                ('code', models.CharField(help_text='Identifiant unique de la pharmacie.', max_length=50, unique=True, verbose_name='Code pharmacie')),
                ('type_pharmacie', models.CharField(choices=[('interne_entreprise', "Pharmacie interne d'entreprise"), ('etablissement', "Pharmacie d'établissement de santé"), ('partenaire', 'Pharmacie partenaire'), ('independante', 'Pharmacie indépendante'), ('hospitaliere', 'Pharmacie hospitalière'), ('autre', 'Autre type de pharmacie')], default='independante', max_length=30, verbose_name='Type de pharmacie')),
                ('pays', models.CharField(default='Guinée', max_length=100, verbose_name='Pays')),
                ('quartier', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quartier')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('nom_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du responsable')),
                ('fonction_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction du responsable')),
                ('numero_ordre_responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'ordre")),
                ('telephone_responsable', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail du responsable')),
                ('numero_agrement', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'agrément")),
                ('numero_autorisation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'autorisation")),
                ('numero_fiscal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro fiscal')),
                ('registre_commerce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registre de commerce')),
                ('statut_partenaire', models.CharField(choices=[('non_partenaire', 'Non partenaire'), ('active', 'Partenaire active'), ('inactive', 'Partenaire inactive'), ('suspendue', 'Partenariat suspendu')], default='non_partenaire', max_length=20, verbose_name='Statut du partenariat')),
                ('accepte_ordonnances_sanita', models.BooleanField(default=True, help_text='Indique si la pharmacie peut recevoir et traiter les ordonnances émises depuis SANITA.', verbose_name='Accepte les ordonnances SANITA')),
                ('date_debut_partenariat', models.DateField(blank=True, null=True, verbose_name='Date de début du partenariat')),
                ('date_fin_partenariat', models.DateField(blank=True, null=True, verbose_name='Date de fin du partenariat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacies/logos/', verbose_name='Logo')),
                ('gestion_stock_active', models.BooleanField(default=True, verbose_name='Gestion du stock active')),
                ('gestion_vente_active', models.BooleanField(default=True, verbose_name='Gestion des ventes active')),
                ('gestion_ordonnance_active', models.BooleanField(default=True, verbose_name='Gestion des ordonnances active')),
                ('gestion_lots_active', models.BooleanField(default=True, verbose_name='Gestion des lots active')),
                ('gestion_inventaire_active', models.BooleanField(default=True, verbose_name='Gestion des inventaires active')),
                ('actif', models.BooleanField(default=True, verbose_name='Pharmacie active')),
                ('etablissement_partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='parametrage_general.etablissementpartenaire', verbose_name='Établissement partenaire')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='parametrage_general.site', verbose_name='Site')),
                ('unite_medicale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='parametrage_general.unitemedicale', verbose_name='Unité médicale')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='parametrage_general.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Pharmacie',
                'verbose_name_plural': 'Pharmacies',
                'db_table': 'pharmacies',
                'ordering': ['nom'],
            },
        ),
    ]
