# Generated by Django 6.1 on 2026-09-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0017_pharmacie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacieInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=191, verbose_name='Nom de la pharmacie')),
                ('code', models.CharField(help_text='Identifiant unique de la pharmacie interne.', max_length=50, unique=True, verbose_name='Code pharmacie')),
                ('localisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('nom_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du responsable')),
                ('fonction_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction du responsable')),
                ('telephone_responsable', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail du responsable')),
                ('gestion_stock_active', models.BooleanField(default=True, verbose_name='Gestion du stock active')),
                ('gestion_lots_active', models.BooleanField(default=True, verbose_name='Gestion des lots active')),
                ('gestion_peremption_active', models.BooleanField(default=True, verbose_name='Gestion des péremptions active')),
                ('gestion_inventaire_active', models.BooleanField(default=True, verbose_name='Gestion des inventaires active')),
                ('gestion_transfert_active', models.BooleanField(default=True, verbose_name='Gestion des transferts active')),
                ('gestion_dispensation_active', models.BooleanField(default=True, verbose_name='Gestion de la dispensation active')),
                ('gestion_vente_active', models.BooleanField(default=False, editable=False, verbose_name='Gestion des ventes active')),
                ('gestion_client_active', models.BooleanField(default=False, editable=False, verbose_name='Gestion des clients active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies_internes', to='parametrage_general.site', verbose_name='Site')),
                ('unite_medicale', models.ForeignKey(blank=True, help_text='Unité médicale à laquelle la pharmacie interne est rattachée, par exemple une infirmerie.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies_internes', to='parametrage_general.unitemedicale', verbose_name='Unité médicale')),
            ],
            options={
                'verbose_name': 'Pharmacie interne',
                'verbose_name_plural': 'Pharmacies internes',
                'db_table': 'pharmacies_internes',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['actif'], name='pharmacies__actif_3a0cec_idx')],
            },
        ),
    ]
