# Generated by Django 6.1 on 2026-09-28 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0018_pharmacieinterne'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmaciePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('nom', models.CharField(max_length=191, verbose_name='Nom de la pharmacie')),
                ('code', models.CharField(help_text='Identifiant unique de la pharmacie partenaire.', max_length=50, unique=True, verbose_name='Code pharmacie')),
                ('pays', models.CharField(default='Guinée', max_length=100, verbose_name='Pays')),
                ('quartier', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quartier')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse e-mail')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('nom_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du responsable')),
                ('fonction_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonction du responsable')),
                ('numero_ordre_responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'ordre")),
                ('telephone_responsable', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone du responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail du responsable')),
                ('numero_agrement', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'agrément")),
                ('numero_autorisation', models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro d'autorisation")),
                ('numero_fiscal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro fiscal')),
                ('registre_commerce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registre de commerce')),
                ('identifiant_administratif', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identifiant administratif')),
                ('statut_partenariat', models.CharField(choices=[('active', 'Partenariat actif'), ('inactive', 'Partenariat inactif'), ('suspendue', 'Partenariat suspendu')], default='active', max_length=20, verbose_name='Statut du partenariat')),
                ('accepte_ordonnances_sanita', models.BooleanField(default=True, help_text='Indique si la pharmacie peut recevoir et traiter les ordonnances émises depuis SANITA.', verbose_name='Accepte les ordonnances SANITA')),
                ('date_debut_partenariat', models.DateField(blank=True, null=True, verbose_name='Date de début du partenariat')),
                ('date_fin_partenariat', models.DateField(blank=True, null=True, verbose_name='Date de fin du partenariat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacies_partenaires/logos/', verbose_name='Logo')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('gestion_catalogue_active', models.BooleanField(default=True, verbose_name='Gestion du catalogue active')),
                ('gestion_tarifs_active', models.BooleanField(default=True, verbose_name='Gestion des tarifs active')),
                ('gestion_stock_active', models.BooleanField(default=True, verbose_name='Gestion du stock active')),
                ('gestion_ordonnance_active', models.BooleanField(default=True, verbose_name='Gestion des ordonnances active')),
                ('gestion_dispensation_active', models.BooleanField(default=True, verbose_name='Gestion de la dispensation active')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies_partenaires', to='parametrage_general.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Pharmacie partenaire',
                'verbose_name_plural': 'Pharmacies partenaires',
                'db_table': 'pharmacies_partenaires',
                'ordering': ['nom'],
            },
        ),
    ]
