# Generated by Django 6.1 on 2026-09-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0019_pharmaciepartenaire'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueMedicamentPharmaciePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_interne', models.CharField(blank=True, help_text='Référence utilisée par la pharmacie pour ce médicament.', max_length=100, null=True, verbose_name='Référence interne')),
                ('nom_commercial', models.CharField(blank=True, help_text='Nom commercial utilisé par la pharmacie, si différent du référentiel SANITA.', max_length=255, null=True, verbose_name='Nom commercial')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('sur_commande', models.BooleanField(default=False, verbose_name='Disponible sur commande')),
                ('unite_vente', models.CharField(blank=True, help_text='Exemple : boîte, flacon, tube, plaquette.', max_length=100, null=True, verbose_name='Unité de vente')),
                ('conditionnement', models.CharField(blank=True, max_length=150, null=True, verbose_name='Conditionnement')),
                ('accepte_ordonnance', models.BooleanField(default=True, verbose_name='Nécessite une ordonnance')),
                ('dispensation_active', models.BooleanField(default=True, verbose_name='Dispensation active')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogues_pharmacies_partenaires', to='stock.medicament', verbose_name='Médicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_medicaments', to='parametrage_general.pharmaciepartenaire', verbose_name='Pharmacie partenaire')),
            ],
            options={
                'verbose_name': 'Médicament du catalogue partenaire',
                'verbose_name_plural': 'Médicaments des catalogues partenaires',
                'db_table': 'catalogue_medicaments_pharmacies_partenaires',
                'ordering': ['pharmacie__nom', 'medicament__nom'],
                'indexes': [models.Index(fields=['pharmacie', 'actif'], name='catalogue_m_pharmac_63f9da_idx'), models.Index(fields=['medicament', 'actif'], name='catalogue_m_medicam_6f0a84_idx')],
                'constraints': [models.UniqueConstraint(fields=('pharmacie', 'medicament'), name='unique_catalogue_pharmacie_medicament')],
            },
        ),
    ]
