# Generated by Django 6.1 on 2026-09-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0020_cataloguemedicamentpharmaciepartenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifMedicamentPharmaciePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="Référence unique permettant d'identifier le tarif.", max_length=100, unique=True, verbose_name='Référence tarifaire')),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix appliqué par la pharmacie partenaire pour le médicament et son conditionnement définis dans le catalogue.', max_digits=15, verbose_name='Prix')),
                ('devise', models.CharField(default='GNF', help_text='Devise dans laquelle le tarif est exprimé.', max_length=10, verbose_name='Devise')),
                ('date_debut', models.DateField(verbose_name='Date de début de validité')),
                ('date_fin', models.DateField(blank=True, help_text="Laisser vide si le tarif reste valable jusqu'à nouvel ordre.", null=True, verbose_name='Date de fin de validité')),
                ('actif', models.BooleanField(default=True, verbose_name='Tarif actif')),
                ('motif', models.CharField(choices=[('creation', 'Création du tarif'), ('revision', 'Révision tarifaire'), ('changement_conditionnement', 'Changement de conditionnement'), ('modification_prix_pharmacie', 'Modification du prix par la pharmacie'), ('renouvellement', 'Renouvellement du tarif'), ('autre', 'Autre')], default='creation', max_length=50, verbose_name='Motif')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifs', to='parametrage_general.cataloguemedicamentpharmaciepartenaire', verbose_name='Médicament du catalogue')),
            ],
            options={
                'verbose_name': 'Tarif de médicament partenaire',
                'verbose_name_plural': 'Tarifs des médicaments partenaires',
                'db_table': 'tarifs_medicaments_pharmacies_partenaires',
                'ordering': ['catalogue__pharmacie__nom', 'catalogue__medicament__nom', '-date_debut'],
                'indexes': [models.Index(fields=['catalogue', 'actif'], name='tarifs_medi_catalog_b14c86_idx'), models.Index(fields=['date_debut', 'date_fin'], name='tarifs_medi_date_de_7cb899_idx'), models.Index(fields=['actif'], name='tarifs_medi_actif_3c1ffc_idx'), models.Index(fields=['devise'], name='tarifs_medi_devise_50e15e_idx')],
            },
        ),
    ]
