# Generated by Django 6.1 on 2026-09-09 11:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parametrage_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact', models.CharField(blank=True, max_length=191, null=True, verbose_name='Contact')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Photo')),
                ('fonction', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction')),
                ('email', models.EmailField(blank=True, max_length=191, null=True, unique=True, verbose_name='Adresse e-mail')),
                ('statut_compte', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('statut_connecte', models.BooleanField(default=False, verbose_name='Connecté')),
                ('statut_log', models.BooleanField(default=True, verbose_name='Journalisation active')),
                ('statut_change_pass', models.BooleanField(default=False, verbose_name='Doit changer le mot de passe')),
                ('statut_d', models.BooleanField(default=True, verbose_name='Statut D')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('reset_code', models.CharField(blank=True, max_length=6, null=True)),
                ('reset_code_expiry', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text="Groupes de l'utilisateur.", related_name='fleet_users', to='auth.group')),
                ('id_societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage_general.societe', verbose_name='Société')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage_general.site', verbose_name='Site')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text="Permissions spécifiques à l'utilisateur.", related_name='fleet_user_permissions', to='auth.permission')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage_general.ville', verbose_name='Ville')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(default=False, verbose_name='Créer')),
                ('can_read', models.BooleanField(default=False, verbose_name='Consulter')),
                ('can_update', models.BooleanField(default=False, verbose_name='Modifier')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Supprimer')),
                ('can_validate', models.BooleanField(default=False, verbose_name='Valider')),
                ('can_assign', models.BooleanField(default=False, verbose_name='Affecter')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.module', verbose_name='Module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.role', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Permission rôle',
                'verbose_name_plural': 'Permissions rôles',
                'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='unique_role_module_permission')],
            },
        ),
    ]
