# Generated by Django 6.1 on 2026-09-09 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('motif', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255)),
                ('date_entree', models.DateTimeField()),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'verbose_name_plural': 'Hospitalisations',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('statut', models.CharField(default='Prévu', max_length=50)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
            },
        ),
        migrations.CreateModel(
            name='CertificatMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Certificat médical',
                'verbose_name_plural': 'Certificats médicaux',
            },
        ),
        migrations.CreateModel(
            name='ArretTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets_travail', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Arrêt de travail',
                'verbose_name_plural': 'Arrêts de travail',
            },
        ),
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actes_medicales', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Acte médical',
                'verbose_name_plural': 'Actes médicaux',
            },
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Historique de consultation',
                'verbose_name_plural': 'Historiques de consultation',
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientations', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Orientation',
                'verbose_name_plural': 'Orientations',
            },
        ),
        migrations.CreateModel(
            name='Referement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referements', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Référencement',
                'verbose_name_plural': 'Référencements',
            },
        ),
        migrations.CreateModel(
            name='SigneVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension', models.CharField(blank=True, max_length=50)),
                ('temperature', models.CharField(blank=True, max_length=50)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signes_vitaux', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Signe vital',
                'verbose_name_plural': 'Signes vitaux',
            },
        ),
    ]
