# Generated by Django 6.1 on 2026-09-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='Clé de licence')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(editable=False, verbose_name="Date d'expiration")),
                ('duration_years', models.PositiveSmallIntegerField(choices=[(1, '1 an'), (2, '2 ans'), (3, '3 ans')], default=1, verbose_name='Durée')),
                ('max_users', models.PositiveIntegerField(default=10, verbose_name="Nombre maximum d'utilisateurs")),
                ('max_sites', models.PositiveIntegerField(default=1, verbose_name='Nombre maximum de sites')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRING_SOON', 'Expire bientôt'), ('EXPIRED', 'Expirée'), ('SUSPENDED', 'Suspendue'), ('CANCELLED', 'Annulée')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Renouvellement automatique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='Numéro du contrat')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name="Date d'expiration")),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant')),
                ('currency', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('EXPIRING_SOON', 'Expire bientôt'), ('EXPIRED', 'Expiré'), ('SUSPENDED', 'Suspendu'), ('CANCELLED', 'Annulé')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Contrat de maintenance',
                'verbose_name_plural': 'Contrats de maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('STANDARD', 'Standard'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix')),
                ('currency', models.CharField(default='GNF', max_length=10, verbose_name='Devise')),
                ('max_users', models.PositiveIntegerField(default=10, verbose_name="Nombre maximum d'utilisateurs")),
                ('max_sites', models.PositiveIntegerField(default=1, verbose_name='Nombre maximum de sites')),
                ('unlimited_users', models.BooleanField(default=False, verbose_name='Utilisateurs illimités')),
                ('unlimited_sites', models.BooleanField(default=False, verbose_name='Sites illimités')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price', 'name'],
            },
        ),
    ]
