# Generated by Django 6.1 on 2026-09-09 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonnement', '0001_initial'),
        ('parametrage_general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_licenses', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='license',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='parametrage_general.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='maintenancecontract',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='maintenancecontract',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_contracts', to='abonnement.license', verbose_name='Licence'),
        ),
        migrations.AddField(
            model_name='maintenancecontract',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_contracts', to='parametrage_general.societe', verbose_name='Société'),
        ),
        migrations.AddField(
            model_name='license',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='abonnement.plan', verbose_name='Plan'),
        ),
    ]
