# Generated by Django 6.1 on 2026-09-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0002_initial'),
        ('parametrage_general', '0004_configurationetablissement_module_conventions_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='societe',
        ),
        migrations.RemoveField(
            model_name='maintenancecontract',
            name='societe',
        ),
        migrations.AddField(
            model_name='license',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='parametrage_general.configurationetablissement', verbose_name='Établissement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancecontract',
            name='etablissement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_contracts', to='parametrage_general.configurationetablissement', verbose_name='Établissement'),
            preserve_default=False,
        ),
    ]
