# Generated by Django 6.1 on 2026-09-09 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage_general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AyantDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENFANT', 'Enfant'), ('CONJOINT', 'Conjoint(e)'), ('AUTRE', 'Autre ayant droit')], default='ENFANT', max_length=20)),
                ('nom', models.CharField(max_length=150)),
                ('prenoms', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lien_parente', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ayants_droit/photos/')),
            ],
            options={
                'verbose_name': 'Ayant droit',
                'verbose_name_plural': 'Ayants droit',
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
            },
        ),
        migrations.CreateModel(
            name='AutreAyantDroit',
            fields=[
                ('ayantdroit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personnels.ayantdroit')),
            ],
            options={
                'verbose_name': 'Autre ayant droit',
                'verbose_name_plural': 'Autres ayants droit',
            },
            bases=('personnels.ayantdroit',),
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('ayantdroit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personnels.ayantdroit')),
                ('certificat_mariage', models.FileField(blank=True, null=True, upload_to='ayants_droit/certificats_mariage/')),
            ],
            options={
                'verbose_name': 'Conjoint',
                'verbose_name_plural': 'Conjoints',
            },
            bases=('personnels.ayantdroit',),
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('ayantdroit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personnels.ayantdroit')),
                ('extrait_naissance', models.FileField(blank=True, null=True, upload_to='ayants_droit/extraits_naissance/')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
            },
            bases=('personnels.ayantdroit',),
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=191, unique=True)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('fonction', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/photos/')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='parametrage_general.departement')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='personnels.employe', verbose_name='Responsable hiérarchique')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='parametrage_general.service')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='parametrage_general.site')),
                ('societe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='parametrage_general.societe')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='parametrage_general.ville')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ayantdroit',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayants_droit', to='personnels.employe', verbose_name='Employé'),
        ),
        migrations.CreateModel(
            name='HistoriqueEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('PROMOTION', 'Promotion'), ('DEPART', 'Départ'), ('CONGES', 'Congés'), ('FORMATION', 'Formation'), ('HABILITATION', 'Habilitation'), ('CHANGEMENT_RESPONSABLE', 'Changement de responsable')], max_length=50, verbose_name="Type d'action")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Détails')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='personnels.employe', verbose_name='Employé')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Utilisateur ayant effectué l'action")),
            ],
            options={
                'verbose_name': 'Historique Employé',
                'verbose_name_plural': 'Historiques Employés',
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['employe', 'date_action'], name='personnels__employe_9b00df_idx')],
            },
        ),
    ]
