# Generated by Django 6.1 on 2026-09-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage_general', '0003_departement_direction'),
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='parametrage_general.fonction'),
        ),
        migrations.AlterModelTable(
            name='employe',
            table='employes',
        ),
    ]
